#!/bin/sh

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

echo "$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_DESTINATION in $KAMAL_RUNTIME seconds"

echo "Running migrations...."
bin/kamal app exec --skip-hooks --reuse --roles=web 'bin/rails db:migrate'

echo "Publishing deployment..."
bin/kamal app exec --skip-hooks --reuse --roles=web 'bin/rails deployment:notify'
